import { Button, VerticalBox, HorizontalBox, TextEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    callback test();

    HorizontalBox {
        Button {
            text: "Post";
            clicked => {
                root.test();
            }

        }
        TextEdit {
            font-size: 14px;
            width: 300px;
            height: 20px;
            text: "What do you wanna squeek?";
        }
    }
}
